## California Housing dataset

    Attribute Information:
    MedInc median income in block group

    HouseAge median house age in block group

    AveRooms average number of rooms per household

    AveBedrms average number of bedrooms per household

    Population block group population

    AveOccup average number of household members

    Latitude block group latitude

    Longitude block group longitude
  https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html

In [43]:
## 1. choosing a machine learning model for regression problem
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [44]:
import pandas as pd
import numpy as np
housing_df=pd.DataFrame(housing['data'], columns=housing['feature_names'])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [45]:
housing_df["Target"]=housing["target"]
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [46]:
len(housing_df)

20640

## Checking null values.

In [47]:
housing_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

In [48]:
housing_df.notnull().sum()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
Target        20640
dtype: int64

In [49]:
housing_df.var()

MedInc        3.609323e+00
HouseAge      1.583963e+02
AveRooms      6.121533e+00
AveBedrms     2.245915e-01
Population    1.282470e+06
AveOccup      1.078700e+02
Latitude      4.562293e+00
Longitude     4.014139e+00
Target        1.331615e+00
dtype: float64

## 1.Linear Models

## 1.1 Ridge regression

In [50]:
# Import algorithm
# split in to x and y
# create x label

from sklearn.model_selection import train_test_split
np.random.seed(42)
x=housing_df.drop("Target",axis=1)
# create y label
y=housing_df["Target"]
# split into tain set and test set
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

#fit the model to the training set
from sklearn.linear_model import Ridge
model=Ridge()
model.fit(x_train,y_train);
# Predict on the test set results

y_pred = model.predict(x_test)


In [51]:
y_pred[:10]

array([0.71923978, 1.76395141, 2.70909238, 2.83897613, 2.60476825,
       2.01179054, 2.64559134, 2.1687701 , 2.74013057, 3.9155685 ])

In [52]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [53]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.533203918257115

In [54]:
model.score(x_train,y_train)

0.61255112452097

In [55]:
model.score(x_test,y_test)

0.5758549611440125

## 1.2 ElasticNet Linear Models

In [56]:
# Import algorithm
# split in to x and y
# create x label

from sklearn.model_selection import train_test_split
np.random.seed(42)
x=housing_df.drop("Target",axis=1)
# create y label
y=housing_df["Target"]
# split into tain set and test set
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

#fit the model to the training set
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression
model=ElasticNet(random_state=0)
model.fit(x_train,y_train);
# Predict on the test set results

y_pred = model.predict(x_test)


In [57]:
y_pred[:10]

array([1.46966793, 1.74416962, 2.23145715, 2.41775198, 2.08991601,
       2.10587399, 2.45621939, 2.12570243, 2.02825213, 3.33271176])

In [58]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [59]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.6762835861380528

In [60]:
model.score(x_train,y_train)

0.42697503980879015

In [61]:
model.score(x_test,y_test)

0.41655189098028245

## 2. Ensemble methods
        The goal of ensemble methods is to combine the predictions of several base estimators built with a given learning algorithm in order to improve generalizability / robustness over a single estimator.

## 2.1 RandomForestRegressor

In [62]:
# Import algorithm
# split in to x and y
# create x label

from sklearn.model_selection import train_test_split
np.random.seed(42)
x=housing_df.drop("Target",axis=1)
# create y label
y=housing_df["Target"]
# split into tain set and test set
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

#fit the model to the training set
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100)
model.fit(x_train,y_train);
# Predict on the test set results

y_pred = model.predict(x_test)


In [63]:
y_pred[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [64]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [65]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.32659871732073664

In [66]:
model.score(x_train,y_train)

0.9736801960414609

In [67]:
model.score(x_test,y_test)

0.8065734772187598

***R-Squared***

In [68]:
from sklearn.metrics import r2_score
y_test_mean=np.full(len(y_test),y_test.mean())

In [69]:
y_test_mean[:10]

array([2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031, 2.0550031,
       2.0550031, 2.0550031, 2.0550031, 2.0550031])

In [70]:
r2_score(y_true=y_test,y_pred=y_test_mean) # model predicting just the mean(),then it will return 0.0

0.0

In [71]:
r2_score(y_true=y_test,y_pred=y_test) #Perfect model returns 1.0 of r2 score

1.0

***Mean Absolute Error(MAE)***
    
    gives an idea of how wrong your model predictions are.

In [72]:
from sklearn.metrics import mean_absolute_error
y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
mae

0.32659871732073664

Our model achieves an MAE of 0.3265. This means, on average our models predictions are 0.3265 units away from the actual value.

***Mean Squared Error (MSE)***

In [73]:
# Mean squared error
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
mse

0.2534678520824551

MSE will always be higher than MAE because is squares the errors rather than only taking the absolute difference into account.

***Cross validation score***
        
        Model is trained on 5 different version of training data and evaluated on 5 different version of the test data.

In [74]:
from sklearn.model_selection import cross_val_score
np.random.seed(42)
cv_acc=cross_val_score(model,x,y,cv=5,scoring=None) #uses default scoring evaluation metrics
print(f"The cross-validated score is: {np.mean(cv_acc)*100:.2f}%")

The cross-validated score is: 65.21%


***R^2***

In [75]:
from sklearn.model_selection import cross_val_score
np.random.seed(42)
cv_acc_r2=cross_val_score(model,x,y,cv=5,scoring="r2") #uses default scoring evaluation metrics
print(f"The cross-validated R^2 score is: {np.mean(cv_acc_r2)*100:.2f}%")

The cross-validated R^2 score is: 65.21%


***neg_mean_absolute_error***

In [76]:
from sklearn.model_selection import cross_val_score
np.random.seed(42)
cv_acc_nmae=cross_val_score(model,x,y,cv=5,scoring="neg_mean_absolute_error") #uses default scoring evaluation metrics
print(f"The cross-validated neg_mean_absolute_error score is: {np.mean(cv_acc_nmae)*100:.2f}%")

The cross-validated neg_mean_absolute_error score is: -46.62%


***neg_mean_squared_error***

In [77]:
from sklearn.model_selection import cross_val_score
np.random.seed(42)
cv_acc_nmse=cross_val_score(model,x,y,cv=5,scoring="neg_mean_squared_error") #uses default scoring evaluation metrics
print(f"The cross-validated neg_mean_squared_error score is: {np.mean(cv_acc_nmse)*100:.2f}%")

The cross-validated neg_mean_squared_error score is: -43.02%
